Repository paketo-buildpacks/azul-zulu, pull requests merged in 2024-04, with the labels that each got.

#401 Add Java 22
  .github/pipeline-descriptor.yml
  .github/workflows/pb-update-jdk-22.yml
  .github/workflows/pb-update-jre-22.yml
  README.md
  buildpack.toml
Labels: type:enhancement, semver:minor

#405 Document BPL_JVM_CLASS_ADJUSTMENT
  README.md
Labels: type:documentation, semver:patch

#416 Add ARM Support for Azul Zulu
  .github/pipeline-descriptor.yml
  .github/workflows/pb-update-jdk-11-arm-64.yml
  .github/workflows/pb-update-jdk-17-arm-64.yml
  .github/workflows/pb-update-jdk-21-arm-64.yml
  .github/workflows/pb-update-jdk-22-arm-64.yml
  .github/workflows/pb-update-jdk-8-arm-64.yml
  .github/workflows/pb-update-jre-11-arm-64.yml
  .github/workflows/pb-update-jre-17-arm-64.yml
  .github/workflows/pb-update-jre-21-arm-64.yml
  .github/workflows/pb-update-jre-22-arm-64.yml
  .github/workflows/pb-update-jre-8-arm-64.yml
  .gitignore
  buildpack.toml
  scripts/build.sh
Labels: type:enhancement, semver:minor

#437 Add arm input for arm64 jobs
  .github/pipeline-descriptor.yml
  .github/workflows/pb-update-jdk-11-arm-64.yml
  .github/workflows/pb-update-jdk-17-arm-64.yml
  .github/workflows/pb-update-jdk-21-arm-64.yml
  .github/workflows/pb-update-jdk-22-arm-64.yml
  .github/workflows/pb-update-jdk-8-arm-64.yml
  .github/workflows/pb-update-jre-11-arm-64.yml
  .github/workflows/pb-update-jre-17-arm-64.yml
  .github/workflows/pb-update-jre-21-arm-64.yml
  .github/workflows/pb-update-jre-22-arm-64.yml
  .github/workflows/pb-update-jre-8-arm-64.yml
Labels: semver:patch, type:bug
